In [1]:
import matplotlib.pyplot as plt
import time
from IPython.display import display
from xml.dom import minidom
import math
import folium
import pandas as pd
from pandas.io.json import json_normalize
import tqdm 
import numpy as np
import geopandas as gpd
import contextily as cx
from random import randint
import json

import warnings
warnings.filterwarnings("ignore")

In [14]:
data= pd.read_excel('Data/Mobility_Survey/kms_matched_responces.xlsx')
data.head()

,Timestamp,per_day,per_week,purpose,route,cost,access,access_time,safety,origin_locality,...,income,income_source,household_size,household_youth,household_cars,og_team_member_id,matched_origin,matching_score,matched_destination,matching_score_d
0,2023-03-06 10:55:22.508,2 times/day - مرتين في اليوم,1 to 2 days per week - يوم إلى يومين في الاسبوع,"Work - للوصول لمكان العمل, School/University ...",عربي- بري,30000.0,Ride with friend - بوصلك صاحبك/ملحة/سيفتي؟,NaN,I only feel safe during daytime - أشعر بالأمان...,Omdurman - أمدرمان,...,"150,000-300,000 pounds - بين 150-300 ألف جنيه",Private Business - عمل خاص,4,0,1,NaN,المهندسين م29,1.0,الخرطوم 3 شرق,0.909
1,2023-03-06 10:56:20.084,Occasionally - أحياناً,1 to 2 days per week - يوم إلى يومين في الاسبوع,"Work - للوصول لمكان العمل, School/University ...",المركز الإسلامي - جامعة السودان العالمية الازهري,4000.0,Walk - عن طريق المشي (كداري),Less than 5 mins - أقل من 5 دقايق,I only feel safe during daytime - أشعر بالأمان...,Khartoum - الخرطوم,...,"100,000-150,000 pounds - بين 100-150 ألف جنيه",Employment - الوظيفة,5,5,2,NaN,الازهري م2-6,1.0,اركويت مربع 59,1.000
2,2023-03-06 11:33:32.494,More than 2 times/day - أكثر من مرتين في اليوم,Everyday - كل أيام الاسبوع,"Work - للوصول لمكان العمل, School/University ...",السوق المركزي - الكدرو,17000.0,Ride with friend - بوصلك صاحبك/ملحة/سيفتي؟,10-20 mins - من 10-20 دقيقة,I only feel safe during daytime - أشعر بالأمان...,Khartoum - الخرطوم,...,"100,000-150,000 pounds - بين 100-150 ألف جنيه",Employment - الوظيفة,3,0,1,NaN,جبرة جنوب م13-14-15-16-17,0.0,الصافية جنوب,0.000
3,2023-03-06 12:15:43.167,More than 2 times/day - أكثر من مرتين في اليوم,3 to 5 days per week - ثلاثه الى خمسه أيام في ...,"Work - للوصول لمكان العمل, School/University ...",صالحة-عربي,30000.0,Walk - عن طريق المشي (كداري),Less than 5 mins - أقل من 5 دقايق,"Yes, I feel safe. - نعم أشعر بالأمان",Omdurman - أمدرمان,...,"300,000-750,000 pounds - بين 300-750 ألف جنيه",Employment - الوظيفة,6,1,1,NaN,صالحة شرق,1.0,المنشية مربع 25,1.000
4,2023-03-06 13:31:31.832,Never - لا استخدم المواصلات,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bahri - بحري,...,"Less than 50,000 pounds - أقل من 50 ألف جنيه",Employment - الوظيفة,69,420,More than 2 - أكثر من 2,NaN,الدروشاب جنوب مربع1,1.0,كافوري,1.000

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6897 entries, 0 to 6896
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Timestamp             6897 non-null   datetime64[ns]
 1   per_day               6897 non-null   object
 2   per_week              5676 non-null   object
 3   purpose               5676 non-null   object
 4   route                 5676 non-null   object
 5   cost                  5676 non-null   float64
 6   access                5676 non-null   object
 7   access_time           5483 non-null   object
 8   safety                5484 non-null   object
 9   origin_locality       6897 non-null   object
 10  origin                6897 non-null   object
 11  destination_locality  6897 non-null   object
 12  destination           6897 non-null   object
 13  start_time            6897 non-null   object
 14  duration              6897 non-null   object
 15  stages                5978 non-null   object
 16  concerns              6897 non-null   object
 17  age                   6897 non-null   object
 18  sex                   6897 non-null   object
 19  employment            6897 non-null   object
 20  income                6897 non-null   object
 21  income_source         6897 non-null   object
 22  household_size        6897 non-null   int64
 23  household_youth       6897 non-null   int64
 24  household_cars        6897 non-null   object
 25  og_team_member_id     716 non-null    float64
 26  matched_origin        6897 non-null   object
 27  matching_score        6897 non-null   float64
 28  matched_destination   6897 non-null   object
 29  matching_score_d      6897 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(2), object(23)
memory usage: 1.6+ MB

In [21]:
mcq_cols= ['purpose', 'concerns']
dummy_df= pd.DataFrame()

for col in mcq_cols:
    data[col]= data[col].astype('category')
    dummy_df= pd.concat([dummy_df, data[col].str.get_dummies(sep=', ')], axis= 1)

In [27]:
data= pd.concat([data, dummy_df], axis= 1)

## Read

In [47]:
data= pd.read_excel('Data/Mobility_Survey/kms_encoded_responces.xlsx')

In [49]:
pd.DataFrame(data.groupby('sex').purpose_moc.value_counts(normalize= True).round(2))

                                                                purpose_moc
sex                                                purpose_moc
Female - أنثى                                      0                   0.92
                                                   1                   0.08
Male -  ذكر                                        0                   0.89
                                                   1                   0.11
Prefer not to answer - افضل عدم الاجابة على هذا... 0                   0.84
                                                   1                   0.16